### ISSUE TITLE
Windows are incorrectly resized, when tiling. 

### ISSUE THREAD

**Issue by DemiLovato69** [nir9/lightwm#10]
### Windows are incorrectly resized, when tiling. 
As shown in the screenshot windows do not size correctly on a 4k display with global scaling set to 150%. 
I'd wager this is a bug with the Windows API when handling the TileWindows function, not taking scaling into account. 

![image](https://github.com/nir9/lightwm/assets/2783997/d2adb826-246c-49f4-a794-2b82aaab9a39)

### Here are the results with scaling set to 100% instead.
![image](https://github.com/nir9/lightwm/assets/2783997/b30d347b-1433-44e8-97c8-7991042f4600)

We can get the device scaling factor with the `GetScaleFactorForDevice` function. 
[MSDN](https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorfordevice)

**Comment by nkxxll** [comment]
`SetProcessDPIAware()` could also be a solution. This is what dwm-win32 window manager uses to overcome this issue I guess.
I will try that method later and if it works I'll make a PR.

**Comment by nir9** [comment]
fixed in #11
