### ISSUE TITLE
Windows Defender false-positive detection for lightwm_dll.dll

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [nir9/lightwm#14]
Windows Defender is incorrectly flagging lightwm_dll.dll as a Trojan (Trojan/Wacatac.H!ml). It's likely that some code within the DLL is triggering this false positive detection.

I recently installed a Windows Defender intelligence update today, but I don't believe this update is causing the detection issue.

I know that this type of false positive detection has been observed with numerous apps in the past, so I understand if this isn't that important.

Nevertheless, I wanted to report this issue to bring it to your attention.

Affected DLL is from release 0.1.0.

Thanks in advance!

![false positive detection](https://github.com/nir9/lightwm/assets/73440604/d4689988-b0e0-4e87-8e70-407dc340022e)
![defender update](https://github.com/nir9/lightwm/assets/73440604/f5cb3254-944f-47dd-82ba-839fa162e1ee)

**Comment by nir9** [comment]
Thanks for reporting, looks like it indeed triggered a machine learning based detector for some reason. Cleaned up the old releases and made a new release 0.2.0 and now it seems to be fixed. If it still occurs let me know

**Comment by IAmTheNerdNextDoor** [comment]
No problem! Windows Defender doesn't seem to detect anything now from the DLL nor the EXE which is great! 

Thank you once again!

**Comment by nir9** [comment]
@AFellowSpeedrunner Awesome, thanks :)
