### ISSUE TITLE
Adding implementation of moving windows to other workspaces

### ISSUE THREAD

**Issue by IAmTheNerdNextDoor** [nir9/lightwm#17]
I thought that we could add this in to the WM as it's slightly annoying having workspaces but not being able to move windows to them. I already implemented this feature in my repo but per your request to discuss new features before we make a pull req or add them into this repo I thought I should ask you first.

In my repo, I made it use Alt+Shift+[1-9]. It's a little buggy still with as it doesn't always move windows to the other workspace but it works well on my main machine running Windows 11.

You click the window you want to move, hit Alt+Shift+2 for example and it moves the window to that workspace and retiles the one you are in. After that you can hit Alt+2 and see the window in that workspace. 

The release exe and dll that I compiled with these changes is 14.5KB combined and debug is 36KB. (minus ilk and pdb files which brings it to 1MB >)

This is my commit in my repo if you want to check my implementation out. I wanted to wait for your approval before I made a pull request.

EDIT: new commit, last one needed a clean up and I needed to set something back, I apologise. it now no longer shows the code I changed and added but I'll send the link to the files. 

https://github.com/AFellowSpeedrunner/lightwm/blob/master/config.h
https://github.com/AFellowSpeedrunner/lightwm/blob/master/keyboard.c
https://github.com/AFellowSpeedrunner/lightwm/blob/master/tiling.h
https://github.com/AFellowSpeedrunner/lightwm/blob/master/tiling.c

(PS. I also fixed a function spelling error too. TOGGLE_FULLSCREEN_MODE_HOYKEY_ID -> TOGGLE_FULLSCREEN_MODE_HOTKEY_ID)

Thanks!

**Comment by nir9** [comment]
Looks good for PR, thanks!

**Comment by IAmTheNerdNextDoor** [comment]
> Looks good for PR, thanks!

Nice, pushing as a PR now!
